export const REQUEST_ACTION_BEGIN = "REQUEST_ACTION_BEGIN";
export const REQUEST_ACTION_FALIURE = "REQUEST_ACTION_FALIURE";
export const SEARCH_QUERY_RESULTS_SUCCESS = "SEARCH_QUERY_RESULTS_SUCCESS";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
